name: Trigger auto deployment for kyro

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '"./Dockefile"/**'
    - '.github/workflows/kyro-AutoDeployTrigger-3c1a5522-a7de-4274-8c0f-50dbb68aead6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: kyro12.azurecr.io
          username: ${{ secrets.KYRO_REGISTRY_USERNAME }}
          password: ${{ secrets.KYRO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kyro12.azurecr.io/kyro:${{ github.sha }}
          file: "./Dockefile"/Dockerfile
          context: "./Dockefile"/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KYRO_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kyro -g Sundar-rg --server kyro12.azurecr.io --username  ${{ secrets.KYRO_REGISTRY_USERNAME }} --password ${{ secrets.KYRO_REGISTRY_PASSWORD }}
            az containerapp update -n kyro -g Sundar-rg --image kyro12.azurecr.io/kyro:${{ github.sha }}
